version: '3'

networks:
  monitoring:
    driver: bridge

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose:
      - 9100
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
  apache:
    image: ubuntu/apache2
    container_name: apache
    volumes:
      - ./status.conf:/etc/apache2/mods-enabled/status.conf
    ports:
      - 8080:80
    networks:
      - monitoring
  apache-exporter:
    image: bitnami/apache-exporter
    container_name: apache-exporter
    ports:
      - 9117:9117
    networks:
      - monitoring
    entrypoint: /bin/apache_exporter --scrape_uri="http://apache:80/server-status?auto"
    